package services

import (
	"fmt"
	"log"
	"net"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
	"waf-backend/database"
)

func isValidIPOrCIDR(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return false
	}
	if net.ParseIP(s) != nil {
		return true
	}
	_, _, err := net.ParseCIDR(s)
	return err == nil
}

var (
	ipSyncMu   sync.Mutex
	vnLocation *time.Location
)

func init() {
	loc, err := time.LoadLocation("Asia/Ho_Chi_Minh")
	if err != nil {
		loc = time.FixedZone("GMT+7", 7*3600)
	}
	vnLocation = loc
}

func VietnamLocation() *time.Location {
	if vnLocation == nil {
		return time.FixedZone("GMT+7", 7*3600)
	}
	return vnLocation
}

func VietnamNow() time.Time {
	return time.Now().In(VietnamLocation())
}

func VietnamNowRFC3339() string {
	return VietnamNow().Format(time.RFC3339)
}

// ParseDurationToExpiration parses user friendly duration string to a future Time
// Supported: "15m", "30m", "1h", "6h", "12h", "24h", "1d", "7d", "permanent"
func ParseDurationToExpiration(dur string) *time.Time {
	dur = strings.ToLower(strings.TrimSpace(dur))
	if dur == "" || dur == "perm" || dur == "permanent" || dur == "forever" || dur == "0" {
		return nil // NULL in DB means Permanent
	}

	var d time.Duration
	var err error

	if strings.HasSuffix(dur, "d") {
		daysStr := strings.TrimSuffix(dur, "d")
		var days int
		if _, scanErr := fmt.Sscanf(daysStr, "%d", &days); scanErr == nil {
			d = time.Duration(days) * 24 * time.Hour
		}
	} else {
		d, err = time.ParseDuration(dur)
	}

	if err != nil && d == 0 {
		return nil
	}

	exp := VietnamNow().Add(d)
	return &exp
}

// SyncIPRulesToFile writes active blacklist & whitelist to HAProxy and Coraza configuration files
func SyncIPRulesToFile() error {
	ipSyncMu.Lock()
	defer ipSyncMu.Unlock()

	if database.DB == nil {
		return nil
	}

	nowRFC := VietnamNowRFC3339()

	// 1. Query Active Blacklist (non-expired)
	blackQuery := `
		SELECT ip FROM ip_rules 
		WHERE rule_type = 'blacklist' 
		  AND (expires_at IS NULL OR expires_at > ?)
		ORDER BY id DESC
	`
	blackRows, err := database.DB.Query(blackQuery, nowRFC)
	if err != nil {
		return fmt.Errorf("failed to query blacklist: %w", err)
	}
	defer blackRows.Close()

	var blackIPs []string
	for blackRows.Next() {
		var ip string
		if err := blackRows.Scan(&ip); err == nil {
			ip = strings.TrimSpace(ip)
			if ip != "" && isValidIPOrCIDR(ip) {
				blackIPs = append(blackIPs, ip)
			}
		}
	}

	// 2. Query Whitelist
	whiteRows, err := database.DB.Query("SELECT ip FROM ip_rules WHERE rule_type = 'whitelist' ORDER BY id DESC")
	if err != nil {
		return fmt.Errorf("failed to query whitelist: %w", err)
	}
	defer whiteRows.Close()

	var whiteIPs []string
	for whiteRows.Next() {
		var ip string
		if err := whiteRows.Scan(&ip); err == nil {
			ip = strings.TrimSpace(ip)
			if ip != "" && isValidIPOrCIDR(ip) {
				whiteIPs = append(whiteIPs, ip)
			}
		}
	}

	// Candidate target directories: inside docker container and local dev paths
	rulesDirs := []string{
		"/app/rules",
		"/etc/coraza-spoa/rules",
		"/usr/local/etc/haproxy/rules",
		"./haproxy/rules",
		"./coraza-spoa/rules",
	}

	blackContent := "# aaWAF IP Blacklist — Auto-generated\n" + strings.Join(blackIPs, "\n") + "\n"
	whiteContent := "# aaWAF IP Whitelist — Auto-generated\n" + strings.Join(whiteIPs, "\n") + "\n"

	for _, dir := range rulesDirs {
		if _, statErr := os.Stat(dir); statErr == nil {
			_ = os.WriteFile(filepath.Join(dir, "blacklist.ips"), []byte(blackContent), 0644)
			_ = os.WriteFile(filepath.Join(dir, "whitelist.ips"), []byte(whiteContent), 0644)
		}
	}

	// Generate Coraza ip_rules.conf
	corazaConf := `# ==========================================
# Coraza Dynamic IP Rules (Generated by aaWAF)
# ==========================================

# 1. Whitelist Bypass (Phase 1)
SecRule REMOTE_ADDR "@ipMatchFromFile /etc/coraza-spoa/rules/whitelist.ips" \
    "id:101,\
    phase:1,\
    nolog,\
    allow,\
    ctl:ruleEngine=Off"

# 2. Blacklist Denial (Phase 1)
SecRule REMOTE_ADDR "@ipMatchFromFile /etc/coraza-spoa/rules/blacklist.ips" \
    "id:102,\
    phase:1,\
    deny,\
    status:403,\
    log,\
    auditlog,\
    msg:'Client IP is blacklisted by Administrator',\
    tag:'ip-blacklist',\
    severity:'CRITICAL'"
`
	corazaDirs := []string{"/etc/coraza-spoa/rules", "./coraza-spoa/rules"}
	for _, dir := range corazaDirs {
		if _, statErr := os.Stat(dir); statErr == nil {
			_ = os.WriteFile(filepath.Join(dir, "ip_rules.conf"), []byte(corazaConf), 0644)
		}
	}

	log.Printf("[IP Sync] Synchronized %d Blacklist and %d Whitelist IPs to HAProxy/Coraza rules.", len(blackIPs), len(whiteIPs))
	reloadWAFEngines()
	return nil
}

// StartIPRulesExpirationDaemon automatically cleans up expired bans and restores normal access
func StartIPRulesExpirationDaemon() {
	go func() {
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		for range ticker.C {
			if database.DB == nil {
				continue
			}

			nowRFC := VietnamNowRFC3339()
			// Find expired blacklist rules
			rows, err := database.DB.Query(
				"SELECT id, ip FROM ip_rules WHERE rule_type = 'blacklist' AND expires_at IS NOT NULL AND expires_at <= ?",
				nowRFC,
			)
			if err != nil {
				continue
			}

			var expiredIDs []int64
			var expiredIPs []string
			for rows.Next() {
				var id int64
				var ip string
				if err := rows.Scan(&id, &ip); err == nil {
					expiredIDs = append(expiredIDs, id)
					expiredIPs = append(expiredIPs, ip)
				}
			}
			rows.Close()

			if len(expiredIDs) > 0 {
				for i, id := range expiredIDs {
					ip := expiredIPs[i]
					_, _ = database.DB.Exec("DELETE FROM ip_rules WHERE id = ?", id)
					log.Printf("[Auto-Unban] IP %s ban duration expired. Automatically unbanned.", ip)

					// Send Telegram notification if enabled
					tgMu.RLock()
					cfg := tgConfig
					tgMu.RUnlock()

					if cfg.Enabled && cfg.BotToken != "" && cfg.ChatID != "" {
						msg := fmt.Sprintf(
							"🔓 <b>[TỰ ĐỘNG GỠ CHẶN IP — COUNTDOWN HOÀN TẤT]</b>\n\n"+
								"• <b>IP:</b> <code>%s</code>\n"+
								"• <b>Trạng thái:</b> Đã hết thời hạn cấm tạm thời.\n"+
								"• <b>Hành động:</b> Tự động gỡ bỏ khỏi Blacklist và khôi phục quyền truy cập trên HAProxy/Coraza.",
							ip,
						)
						go func(text string) {
							_ = SendTelegramMessage(cfg.BotToken, cfg.ChatID, text)
						}(msg)
					}
				}

				// Re-sync configuration files to remove unbanned IPs
				_ = SyncIPRulesToFile()
			}
		}
	}()
}
