package services

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"waf-backend/database"
)

var rulesSyncMu sync.Mutex

// SyncCustomRulesToFile writes all active custom rules to custom_rules.conf and reloads Coraza SPOA
func SyncCustomRulesToFile() error {
	rulesSyncMu.Lock()
	defer rulesSyncMu.Unlock()

	if database.DB == nil {
		return nil
	}

	rows, err := database.DB.Query(`
		SELECT rule_id, name, description, sec_rule 
		FROM custom_rules 
		WHERE enabled = 1 
		ORDER BY id ASC
	`)
	if err != nil {
		return fmt.Errorf("failed to query custom rules: %w", err)
	}
	defer rows.Close()

	var sb strings.Builder
	sb.WriteString("# ==========================================\n")
	sb.WriteString("# Custom WAF Rules (Auto-generated by aaWAF Dashboard)\n")
	sb.WriteString("# ==========================================\n\n")

	count := 0
	for rows.Next() {
		var ruleID int
		var name, desc, secRule string
		if err := rows.Scan(&ruleID, &name, &desc, &secRule); err == nil {
			count++
			sb.WriteString(fmt.Sprintf("# Rule %d: %s\n", ruleID, name))
			if desc != "" {
				sb.WriteString(fmt.Sprintf("# Description: %s\n", desc))
			}
			trimmed := strings.TrimSpace(secRule)
			sb.WriteString(trimmed)
			sb.WriteString("\n\n")
		}
	}

	content := sb.String()

	targetPaths := []string{
		"/etc/coraza-spoa/rules/custom_rules.conf",
		"/app/coraza-spoa/rules/custom_rules.conf",
		"./coraza-spoa/rules/custom_rules.conf",
	}

	written := 0
	for _, p := range targetPaths {
		dir := filepath.Dir(p)
		if _, statErr := os.Stat(dir); statErr == nil {
			if err := os.WriteFile(p, []byte(content), 0644); err == nil {
				written++
				log.Printf("[Rules Sync] Written %d custom rules to %s", count, p)
			}
		}
	}

	if written == 0 {
		log.Printf("[Rules Sync] Warning: could not find target directory to write custom_rules.conf")
	}

	// Graceful reload or restart coraza-spoa container so new rules take effect
	go reloadCorazaSPOA()

	return nil
}

func reloadCorazaSPOA() {
	// Try SIGHUP or restart coraza-spoa container
	cmd := exec.Command("docker", "kill", "--signal=HUP", "coraza-spoa")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[Coraza Reload] SIGHUP signal sent to coraza-spoa: %s", strings.TrimSpace(string(out)))
		return
	}

	cmd = exec.Command("docker", "restart", "coraza-spoa")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[Coraza Reload] docker restart coraza-spoa successful: %s", strings.TrimSpace(string(out)))
		return
	}

	log.Printf("[Coraza Reload] Notice: coraza-spoa container reload skipped (rules saved to file).")
}
