package services

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"text/template"
	"waf-backend/database"
)

var sitesSyncMu sync.Mutex

// ProtectedSiteForSync holds site data used in HAProxy config generation
type ProtectedSiteForSync struct {
	ID             int64
	Name           string
	Domain         string
	UpstreamTarget string
	Port           int
	SSLEnabled     bool
	WAFMode        string // "prevention", "detection", "bypass"
	Status         string // "active", "disabled"
}

// haproxyConfigTemplate is the Go template for generating a complete haproxy.cfg
// It dynamically creates ACLs + backends per protected site from the database
const haproxyConfigTemplate = `# ================================================================
# HAProxy Configuration — Auto-generated by aaWAF Engine
# DO NOT EDIT MANUALLY — Changes will be overwritten on next sync
# ================================================================

global
    log stdout format raw local0

defaults
    log global
    mode http
    option httplog
    timeout client 1m
    timeout server 1m
    timeout connect 10s
    errorfile 403 /usr/local/etc/haproxy/errors/403.http

frontend default
    mode http
    bind *:80
    log-format "%ci:%cp [%t] %ft %b/%s %ST %B %{+Q}r %[var(txn.coraza.id)] spoa-error:%[var(txn.coraza.error)] waf-action:%[var(txn.coraza.action)]"

    # ========================================
    # IP Access Control (Fast-Path Enforcement)
    # ========================================
    acl is_whitelisted src -f /usr/local/etc/haproxy/rules/whitelist.ips
    acl is_blacklisted src -f /usr/local/etc/haproxy/rules/blacklist.ips
    http-request deny deny_status 403 hdr "X-Blocked-By" "HAProxy-IP-Blacklist" if is_blacklisted !is_whitelisted

    # ========================================
    # SPOE Coraza WAF Engine Setup
    # ========================================
    http-request set-var(txn.coraza.app) str(sample_app)
    filter spoe engine coraza config /usr/local/etc/haproxy/spoe-coraza.conf
{{- if .HasBypassSites }}

    # Sites with WAF Bypass mode — skip SPOE inspection
{{- range .BypassSites }}
    acl waf_bypass_site_{{ .ID }} hdr(host) -i {{ .Domain }}
{{- end }}
    http-request send-spoe-group coraza coraza-req if !is_whitelisted{{ range .BypassSites }} !waf_bypass_site_{{ .ID }}{{ end }}
{{- else }}
    http-request send-spoe-group coraza coraza-req if !is_whitelisted
{{- end }}

    # WAF Action Handlers
    http-request redirect code 302 location %[var(txn.coraza.data)] if { var(txn.coraza.action) -m str redirect }
    http-response redirect code 302 location %[var(txn.coraza.data)] if { var(txn.coraza.action) -m str redirect }
    http-request deny deny_status 403 hdr "X-Blocked-By" "Coraza-WAF-Shield" if { var(txn.coraza.action) -m str deny }
    http-response deny deny_status 403 hdr "X-Blocked-By" "Coraza-WAF-Shield" if { var(txn.coraza.action) -m str deny }
    http-request silent-drop if { var(txn.coraza.action) -m str drop }
    http-response silent-drop if { var(txn.coraza.action) -m str drop }

    # ========================================
    # Virtual Host Routing (Auto-generated)
    # ========================================
{{- range .Sites }}
    # Site #{{ .ID }}: {{ .Name }} [WAF: {{ .WAFMode }}]
    acl host_site_{{ .ID }} hdr(host) -i {{ .Domain }}
    use_backend backend_site_{{ .ID }} if host_site_{{ .ID }}
{{ end }}
    default_backend protected-app-backend

# ========================================
# Backend Definitions (Auto-generated)
# ========================================
{{- range .Sites }}

# Backend: {{ .Name }} ({{ .Domain }}) → {{ .UpstreamTarget }}
backend backend_site_{{ .ID }}
    mode http
    server origin_{{ .ID }} {{ .UpstreamTarget }} check inter 5s fall 3 rise 2
{{- end }}

# Default fallback backend (Demo Web Application)
backend protected-app-backend
    mode http
    server web_app protected-app:80 check

# SPOE Coraza TCP backend
backend spoe-coraza
    mode tcp
    balance roundrobin
    timeout connect 5s
    timeout server 3m
    server spoa coraza-spoa:9000

# HAProxy Internal Prometheus/CSV Stats (accessed by waf-backend)
listen stats
    bind :8404
    mode http
    stats enable
    stats uri /
    stats refresh 5s
`

// templateData holds all data passed to the HAProxy config template
type templateData struct {
	Sites          []ProtectedSiteForSync
	HasBypassSites bool
	BypassSites    []ProtectedSiteForSync
}

// SyncSitesToHAProxy reads all active protected sites from the database,
// renders a complete haproxy.cfg using Go templates, writes it to disk,
// and triggers a graceful HAProxy reload.
func SyncSitesToHAProxy() error {
	sitesSyncMu.Lock()
	defer sitesSyncMu.Unlock()

	if database.DB == nil {
		return fmt.Errorf("database not initialized")
	}

	// 1. Query all active protected sites from the database
	rows, err := database.DB.Query(`
		SELECT id, name, domain, upstream_target, port, ssl_enabled, waf_mode, status
		FROM protected_sites
		WHERE status = 'active'
		ORDER BY id ASC
	`)
	if err != nil {
		return fmt.Errorf("failed to query protected sites: %w", err)
	}
	defer rows.Close()

	var sites []ProtectedSiteForSync
	var bypassSites []ProtectedSiteForSync

	for rows.Next() {
		var s ProtectedSiteForSync
		var sslInt int
		if err := rows.Scan(&s.ID, &s.Name, &s.Domain, &s.UpstreamTarget, &s.Port, &sslInt, &s.WAFMode, &s.Status); err != nil {
			log.Printf("[Sites Sync] Warning: failed to scan site row: %v", err)
			continue
		}
		s.SSLEnabled = sslInt == 1

		// Normalize WAF mode
		if s.WAFMode == "" {
			s.WAFMode = "prevention"
		}

		sites = append(sites, s)

		// Collect bypass sites for WAF skip ACL
		if s.WAFMode == "bypass" {
			bypassSites = append(bypassSites, s)
		}
	}

	// 2. Prepare template data
	data := templateData{
		Sites:          sites,
		HasBypassSites: len(bypassSites) > 0,
		BypassSites:    bypassSites,
	}

	// 3. Parse and execute the HAProxy config template
	tmpl, err := template.New("haproxy").Parse(haproxyConfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse HAProxy config template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to render HAProxy config: %w", err)
	}

	configContent := buf.String()

	// 4. Write the generated config to all known HAProxy config paths
	configPaths := []string{
		"/usr/local/etc/haproxy/haproxy.cfg", // Inside HAProxy container (shared volume)
		"/app/haproxy/haproxy.cfg",           // Inside backend container (shared volume)
		"./haproxy/haproxy.cfg",              // Local dev path
	}

	writtenCount := 0
	for _, cfgPath := range configPaths {
		dir := filepath.Dir(cfgPath)
		if _, statErr := os.Stat(dir); statErr != nil {
			continue
		}
		if err := os.WriteFile(cfgPath, []byte(configContent), 0644); err != nil {
			log.Printf("[Sites Sync] Warning: failed to write %s: %v", cfgPath, err)
		} else {
			writtenCount++
			log.Printf("[Sites Sync] Written HAProxy config to %s", cfgPath)
		}
	}

	if writtenCount == 0 {
		return fmt.Errorf("could not write HAProxy config to any target path")
	}

	log.Printf("[Sites Sync] Generated HAProxy config with %d active sites (%d bypass)", len(sites), len(bypassSites))

	// 5. Trigger HAProxy graceful reload
	if err := reloadHAProxy(); err != nil {
		log.Printf("[Sites Sync] Warning: HAProxy reload failed: %v (config was written successfully, will take effect on next restart)", err)
		// Don't return error — config is already written, just reload failed
	}

	return nil
}

// reloadHAProxy attempts to trigger a graceful HAProxy reload using multiple strategies
func reloadHAProxy() error {
	// Strategy 1: Send SIGHUP to haproxy container via Docker CLI
	cmd := exec.Command("docker", "kill", "--signal=HUP", "haproxy")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[HAProxy Reload] SIGHUP signal sent to haproxy successfully: %s", strings.TrimSpace(string(out)))
		return nil
	} else {
		log.Printf("[HAProxy Reload] Docker HUP attempt: %v — %s", err, strings.TrimSpace(string(out)))
	}

	// Strategy 2: docker restart haproxy (fallback if HUP fails)
	cmd = exec.Command("docker", "restart", "haproxy")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[HAProxy Reload] Docker restart haproxy successful: %s", strings.TrimSpace(string(out)))
		return nil
	} else {
		log.Printf("[HAProxy Reload] Docker restart attempt: %v — %s", err, strings.TrimSpace(string(out)))
	}

	// Strategy 3: Direct kill -HUP if host pidof is accessible
	cmd = exec.Command("sh", "-c", "pidof haproxy && kill -HUP $(pidof haproxy)")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[HAProxy Reload] Direct HUP signal sent: %s", strings.TrimSpace(string(out)))
		return nil
	}

	log.Printf("[HAProxy Reload] Notice: Reload signal could not be sent directly from this process. Config is saved and will be active on next restart.")
	return nil
}
