package services

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"text/template"
	"waf-backend/database"
)

var sitesSyncMu sync.Mutex

// ProtectedSiteForSync holds site data used in HAProxy config generation
type ProtectedSiteForSync struct {
	ID             int64
	Name           string
	Domain         string
	UpstreamTarget string
	Port           int
	SSLEnabled     bool
	WAFMode        string // "prevention", "detection", "bypass"
	Status         string // "active", "disabled"
}

// haproxyConfigTemplate is the Go template for generating a complete haproxy.cfg
// It dynamically creates ACLs + backends per protected site from the database
const haproxyConfigTemplate = `# ================================================================
# HAProxy Configuration — Auto-generated by aaWAF Engine
# DO NOT EDIT MANUALLY — Changes will be overwritten on next sync
# ================================================================

global
    log stdout format raw local0

defaults
    log global
    mode http
    option httplog
    timeout client 1m
    timeout server 1m
    timeout connect 10s
    errorfile 403 /usr/local/etc/haproxy/errors/403.http

frontend default
    mode http
    bind *:80
    log-format "%ci:%cp [%t] %ft %b/%s %ST %B %{+Q}r %[var(txn.coraza.id)] spoa-error:%[var(txn.coraza.error)] waf-action:%[var(txn.coraza.action)]"

    # ========================================
    # IP Access Control (Fast-Path Enforcement)
    # ========================================
    acl is_whitelisted src -f /usr/local/etc/haproxy/rules/whitelist.ips
    acl is_blacklisted src -f /usr/local/etc/haproxy/rules/blacklist.ips
    http-request deny deny_status 403 hdr "X-Blocked-By" "HAProxy-IP-Blacklist" if is_blacklisted !is_whitelisted

    # ========================================
    # Internal Challenge & API Gateway
    # ========================================
    acl is_waf_challenge path_beg /waf-challenge /api/challenge
    use_backend backend_waf_internal if is_waf_challenge

{{- if .BlockScanners }}
    # ========================================
    # Scanner & Malicious Bot Defense
    # ========================================
    acl is_scanner_agent hdr_sub(user-agent) -i sqlmap nikto acunetix nessus masscan gobuster dirbuster wpscan
    http-request deny deny_status 403 hdr "X-Blocked-By" "aaWAF-Scanner-Shield" if is_scanner_agent !is_whitelisted
{{- end }}

{{- if .CCEnabled }}
    # ========================================
    # CC Defense & HTTP Flood Stick-Table
    # ========================================
    stick-table type ip size 100k expire 10s store http_req_rate(10s)
    http-request track-sc0 src if !is_whitelisted
    acl is_cc_flooding sc0_http_req_rate gt {{ .CCThreshold }}
    acl has_waf_clearance req.cook(waf_clearance) -m found

{{- if eq .CCAction "block_429" }}
    http-request deny deny_status 429 hdr "X-Blocked-By" "aaWAF-CC-Shield" if is_cc_flooding !is_whitelisted !has_waf_clearance !is_waf_challenge
{{- else if eq .CCAction "auto_ban" }}
    http-request deny deny_status 403 hdr "X-Blocked-By" "aaWAF-CC-Shield-AutoBan" if is_cc_flooding !is_whitelisted !has_waf_clearance !is_waf_challenge
{{- else }}
    # Default Action: Challenge Mode (Redirect to /waf-challenge)
    http-request redirect code 302 location /waf-challenge?return_url=%[path] if is_cc_flooding !is_whitelisted !has_waf_clearance !is_waf_challenge
{{- end }}
{{- end }}

    # ========================================
    # SPOE Coraza WAF Engine Setup
    # ========================================
    http-request set-var(txn.coraza.app) str(sample_app)
    filter spoe engine coraza config /usr/local/etc/haproxy/spoe-coraza.conf
{{- if .HasBypassSites }}

    # Sites with WAF Bypass mode — skip SPOE inspection completely
{{- range .BypassSites }}
    acl is_waf_bypass_mode hdr_beg(host) -i {{ .Domain }}
{{- end }}
    http-request set-var(txn.is_waf_bypass) bool(1) if is_waf_bypass_mode
    http-request send-spoe-group coraza coraza-req if !is_whitelisted !is_waf_bypass_mode
{{- else }}
    http-request send-spoe-group coraza coraza-req if !is_whitelisted
{{- end }}

{{- if .HasDetectionSites }}

    # Sites with WAF Detection (Monitor Only) mode — inspect & log, but bypass 403 blocking
{{- range .DetectionSites }}
    acl is_waf_detection_mode hdr_beg(host) -i {{ .Domain }}
{{- end }}
    http-request set-var(txn.is_waf_detection) bool(1) if is_waf_detection_mode
{{- end }}

    # WAF Action Handlers
    http-request redirect code 302 location %[var(txn.coraza.data)] if { var(txn.coraza.action) -m str redirect }
    http-response redirect code 302 location %[var(txn.coraza.data)] if { var(txn.coraza.action) -m str redirect }
{{- if .HasDetectionSites }}
    # In Detection mode, inject headers for upstream visibility but do NOT block with 403
    http-request set-header X-WAF-Mode "Detection-Only" if is_waf_detection_mode
    http-request set-header X-WAF-Threat-Detected "True" if is_waf_detection_mode { var(txn.coraza.action) -m str deny }
{{- end }}
    http-request deny deny_status 403 hdr "X-Blocked-By" "Coraza-WAF-Shield" if { var(txn.coraza.action) -m str deny }{{ if .HasDetectionSites }} !is_waf_detection_mode{{ end }}{{ if .HasBypassSites }} !is_waf_bypass_mode{{ end }}
    http-response deny deny_status 403 hdr "X-Blocked-By" "Coraza-WAF-Shield" if { var(txn.coraza.action) -m str deny }{{ if .HasDetectionSites }} !{ var(txn.is_waf_detection) -m bool }{{ end }}{{ if .HasBypassSites }} !{ var(txn.is_waf_bypass) -m bool }{{ end }}
    http-request silent-drop if { var(txn.coraza.action) -m str drop }{{ if .HasDetectionSites }} !is_waf_detection_mode{{ end }}{{ if .HasBypassSites }} !is_waf_bypass_mode{{ end }}
    http-response silent-drop if { var(txn.coraza.action) -m str drop }{{ if .HasDetectionSites }} !{ var(txn.is_waf_detection) -m bool }{{ end }}{{ if .HasBypassSites }} !{ var(txn.is_waf_bypass) -m bool }{{ end }}

    # ========================================
    # Virtual Host Routing (Auto-generated)
    # ========================================
{{- range .Sites }}
    # Site #{{ .ID }}: {{ .Name }} [WAF: {{ .WAFMode }}]
    acl host_site_{{ .ID }} hdr_beg(host) -i {{ .Domain }}
    use_backend backend_site_{{ .ID }} if host_site_{{ .ID }}
{{ end }}
    default_backend protected-app-backend

# ========================================
# Backend Definitions (Auto-generated)
# ========================================

# Backend: aaWAF Internal Engine (Challenge & API Gateway)
backend backend_waf_internal
    mode http
    server waf_core waf-backend:8080 check

{{- range .Sites }}

# Backend: {{ .Name }} ({{ .Domain }}) → {{ .UpstreamTarget }}
backend backend_site_{{ .ID }}
    mode http
    server origin_{{ .ID }} {{ .UpstreamTarget }} check inter 5s fall 3 rise 2
{{- end }}

# Default fallback backend (Demo Web Application)
backend protected-app-backend
    mode http
    server web_app protected-app:80 check

# SPOE Coraza TCP backend
backend spoe-coraza
    mode tcp
    balance roundrobin
    timeout connect 5s
    timeout server 3m
    server spoa coraza-spoa:9000

# HAProxy Internal Prometheus/CSV Stats (accessed by waf-backend)
listen stats
    bind :8404
    mode http
    stats enable
    stats uri /
    stats refresh 5s
`

// templateData holds all data passed to the HAProxy config template
type templateData struct {
	Sites             []ProtectedSiteForSync
	HasBypassSites    bool
	BypassSites       []ProtectedSiteForSync
	HasDetectionSites bool
	DetectionSites    []ProtectedSiteForSync
	// Bot Defense & CC Mitigation
	CCEnabled         bool
	CCThreshold       int
	CCAction          string
	BlockScanners     bool
}

// SyncSitesToHAProxy reads all active protected sites and bot defense settings from the database,
// renders a complete haproxy.cfg using Go templates, writes it to disk,
// and triggers a graceful HAProxy reload.
func SyncSitesToHAProxy() error {
	sitesSyncMu.Lock()
	defer sitesSyncMu.Unlock()

	if database.DB == nil {
		return fmt.Errorf("database not initialized")
	}

	// 1. Query all active protected sites from the database
	rows, err := database.DB.Query(`
		SELECT id, name, domain, upstream_target, port, ssl_enabled, waf_mode, status
		FROM protected_sites
		WHERE status = 'active'
		ORDER BY id ASC
	`)
	if err != nil {
		return fmt.Errorf("failed to query protected sites: %w", err)
	}
	defer rows.Close()

	var sites []ProtectedSiteForSync
	var bypassSites []ProtectedSiteForSync
	var detectionSites []ProtectedSiteForSync

	for rows.Next() {
		var s ProtectedSiteForSync
		var sslInt int
		if err := rows.Scan(&s.ID, &s.Name, &s.Domain, &s.UpstreamTarget, &s.Port, &sslInt, &s.WAFMode, &s.Status); err != nil {
			log.Printf("[Sites Sync] Warning: failed to scan site row: %v", err)
			continue
		}
		s.SSLEnabled = sslInt == 1

		// Normalize WAF mode
		if s.WAFMode == "" {
			s.WAFMode = "prevention"
		}

		sites = append(sites, s)

		// Collect sites by WAF enforcement mode
		if s.WAFMode == "bypass" {
			bypassSites = append(bypassSites, s)
		} else if s.WAFMode == "detection" {
			detectionSites = append(detectionSites, s)
		}
	}

	// 2. Query Bot Defense settings
	var ccEnabledStr, ccThresholdStr, ccActionStr, blockScannersStr string
	_ = database.DB.QueryRow("SELECT value FROM settings WHERE key = 'bot_cc_enabled'").Scan(&ccEnabledStr)
	_ = database.DB.QueryRow("SELECT value FROM settings WHERE key = 'bot_cc_threshold'").Scan(&ccThresholdStr)
	_ = database.DB.QueryRow("SELECT value FROM settings WHERE key = 'bot_cc_action'").Scan(&ccActionStr)
	_ = database.DB.QueryRow("SELECT value FROM settings WHERE key = 'bot_block_scanners'").Scan(&blockScannersStr)

	ccThreshold := 50
	if val, scanErr := strconv.Atoi(ccThresholdStr); scanErr == nil && val > 0 {
		ccThreshold = val
	}
	ccAction := "challenge"
	if ccActionStr != "" {
		ccAction = ccActionStr
	}
	ccEnabled := (ccEnabledStr != "false")
	blockScanners := (blockScannersStr != "false")

	// 3. Prepare template data
	data := templateData{
		Sites:             sites,
		HasBypassSites:    len(bypassSites) > 0,
		BypassSites:       bypassSites,
		HasDetectionSites: len(detectionSites) > 0,
		DetectionSites:    detectionSites,
		CCEnabled:         ccEnabled,
		CCThreshold:       ccThreshold,
		CCAction:          ccAction,
		BlockScanners:     blockScanners,
	}

	// 3. Parse and execute the HAProxy config template
	tmpl, err := template.New("haproxy").Parse(haproxyConfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse HAProxy config template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to render HAProxy config: %w", err)
	}

	configContent := buf.String()

	// 4. Write the generated config to all known HAProxy config paths
	configPaths := []string{
		"/usr/local/etc/haproxy/haproxy.cfg", // Inside HAProxy container (shared volume)
		"/app/haproxy/haproxy.cfg",           // Inside backend container (shared volume)
		"./haproxy/haproxy.cfg",              // Local dev path
	}

	writtenCount := 0
	for _, cfgPath := range configPaths {
		dir := filepath.Dir(cfgPath)
		if _, statErr := os.Stat(dir); statErr != nil {
			continue
		}
		if err := os.WriteFile(cfgPath, []byte(configContent), 0644); err != nil {
			log.Printf("[Sites Sync] Warning: failed to write %s: %v", cfgPath, err)
		} else {
			writtenCount++
			log.Printf("[Sites Sync] Written HAProxy config to %s", cfgPath)
		}
	}

	if writtenCount == 0 {
		return fmt.Errorf("could not write HAProxy config to any target path")
	}

	log.Printf("[Sites Sync] Generated HAProxy config with %d active sites (%d bypass)", len(sites), len(bypassSites))

	// 5. Trigger HAProxy graceful reload
	if err := reloadHAProxy(); err != nil {
		log.Printf("[Sites Sync] Warning: HAProxy reload failed: %v (config was written successfully, will take effect on next restart)", err)
		// Don't return error — config is already written, just reload failed
	}

	return nil
}

// reloadHAProxy attempts to trigger a graceful HAProxy reload using multiple strategies
func reloadHAProxy() error {
	// Strategy 1: Send SIGHUP to haproxy container via Docker CLI
	cmd := exec.Command("docker", "kill", "--signal=HUP", "haproxy")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[HAProxy Reload] SIGHUP signal sent to haproxy successfully: %s", strings.TrimSpace(string(out)))
		return nil
	} else {
		log.Printf("[HAProxy Reload] Docker HUP attempt: %v — %s", err, strings.TrimSpace(string(out)))
	}

	// Strategy 2: docker restart haproxy (fallback if HUP fails)
	cmd = exec.Command("docker", "restart", "haproxy")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[HAProxy Reload] Docker restart haproxy successful: %s", strings.TrimSpace(string(out)))
		return nil
	} else {
		log.Printf("[HAProxy Reload] Docker restart attempt: %v — %s", err, strings.TrimSpace(string(out)))
	}

	// Strategy 3: Direct kill -HUP if host pidof is accessible
	cmd = exec.Command("sh", "-c", "pidof haproxy && kill -HUP $(pidof haproxy)")
	if out, err := cmd.CombinedOutput(); err == nil {
		log.Printf("[HAProxy Reload] Direct HUP signal sent: %s", strings.TrimSpace(string(out)))
		return nil
	}

	log.Printf("[HAProxy Reload] Notice: Reload signal could not be sent directly from this process. Config is saved and will be active on next restart.")
	return nil
}

// reloadWAFEngines reloads both Tier 1 (HAProxy) and Tier 2 (Coraza SPOA) concurrently
func reloadWAFEngines() {
	_ = reloadHAProxy()
	reloadCorazaSPOA()
}

