[coraza]
spoe-agent coraza-agent
    messages coraza-req coraza-res
    option var-prefix coraza
    option set-on-error error
    timeout hello      500ms
    timeout idle       30s
    timeout processing 2000ms
    use-backend spoe-coraza

spoe-message coraza-req
    args id=unique-id src-ip=src src-port=src_port method=method path=path query=query version=req.ver headers=req.hdrs body=req.body
    event on-frontend-http-request

spoe-message coraza-res
    args id=unique-id version=res.ver status=status headers=res.hdrs body=res.body
    event on-http-response
